module.exports = {
  anime: require("./anime"),
  bumplb: require("./bumplb"),
  bumpoff: require("./bumpoff"),
  bumpon: require("./bumpon"),
  bumpreminder: require("./bumpreminder"),
  char: require("./char"),
  cuddle: require("./cuddle"),
  episodes: require("./episodes"),
  help: require("./help"),
  hug: require("./hug"),
  kiss: require("./kiss"),
  manga: require("./manga"),
  meow: require("./meow"),
  pat: require("./pat"),
  poke: require("./poke"),
  reactionrole: require("./reactionrole"),
  roleadd: require("./roleadd"),
  roleremove: require("./roleremove"),
  schedule: require("./schedule"),
  season: require("./season"),
  slap: require("./slap"),
  smug: require("./smug"),
  tickle: require("./tickle"),
  top: require("./top"),
  user: require("./user"),
};
